require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '10.0'

target 'CrossPlatform' do
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  target 'CrossPlatformTests' do
    inherit! :complete
    # Pods for testing
    pod 'boost-for-react-native', :git => 'https://gitee.com/mirrors/boost-for-react-native.git’
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  # use_flipper!({ 'Flipper-Folly' => '2.3.0' })
  # post_install do |installer|
  #   flipper_post_install(installer)
  # end
end

target 'CrossPlatform-tvOS' do
  # Pods for CrossPlatform-tvOS

  target 'CrossPlatform-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end
